db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/persons_db
  login: postgres
  password: postgres

liquibase:
  enabled: false
  changelog: classpath:db/changelog/db.changelog-master.yml
  drop: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
